#!/usr/bin/env python

import rospy
from geometry_msgs.msg import Twist


def set_new_velocity(message):
    print('Got new velocity:')
    print(message)


def main():
    rospy.init_node('controller')
    rospy.Subscriber('cmd_vel', Twist, set_new_velocity)

    rospy.spin()


if __name__ == '__main__':
    main()
